{% set name = "conda-package-streaming" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 1
  noarch: python

requirements:
  host:
    - flit-core
    - python >=3.7
    - pip
  run:
    - zstandard >=0.15
    - requests
    - python >=3.7

test:
  imports:
    - conda_package_streaming.url
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda/conda-package-streaming
  summary: Download metadata from conda packages without transferring entire file.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-package-streaming/
  dev_url: https://github.com/conda/conda-package-streaming

extra:
  recipe-maintainers:
    - dholth
